### ISSUE TITLE
Map<TIn, TOut>(src, dest)

### ISSUE THREAD

**Issue by dbones** [DogusTeknoloji/BatMap#2]
apply mapping to an existing object.

*possible use-case*
user posts an update (using a DTO) to an existing object. the service loads the existing object from the DB, and then use the map(dto, entity) to apply the updates as required.

*Example Usage*

    public void Update(PersonDto personDto) {
        var person = _session.Get<Person>(personDto.id);
        _mapper.Map(personDto, person);
    }

note that the dto may only contain a subset of the entity properties

**Comment by umutozel** [comment]
Great idea, thanks!

**Comment by umutozel** [comment]
I've added the method as "MapTo" to avoid signature conflicts.
Can be used like this;

    public void Update(PersonDto personDto) {
        var person = _session.Get<Person>(personDto.id);
        _mapper.MapTo(personDto, person);
    }

[Nuget package](https://www.nuget.org/packages/BatMap/) (0.1.108).
@dbones can you check the latest package?

**Comment by dbones** [comment]
nice one, I should be able to check later in the week (sorry that I cannot do it sooner)

**Comment by umutozel** [comment]
I'm closing this for now, you can open again if you experience any problems.
