### ISSUE TITLE
A bit strange benchmark results

### ISSUE THREAD

**Issue by GSerjo** [DogusTeknoloji/BatMap#3]
It's a bit strange that `HandWritten` is not the first. `BatMap` is a really nice project, but benchmark result looks a bit strange. Looks like `HandWritten`sample has a bug, yes it's possible to do this kind of mapping but it's a bit inefficient. try to use `ConverAll` method, it'll remove all `ToList` methods (except one, IList does not have `ConvertAll`

like this

```
public void HandWritten()
{
	var customerDTOs = _customers.Select(c => new CustomerDTO
	{
		Id = c.Id,
		Addresses = c.Addresses.ConvertAll(a => new AddressDTO
		{
			City = new CityDTO
			{
				Id = a.City.Id,
				Name = a.City.Name,
				Population = a.City.Population
			},
			Detail = a.Detail,
			Id = a.Id
		}),
		CompanyName = c.CompanyName,
		Endorsement = c.Endorsement,
		Orders = c.Orders.ConvertAll(o => new OrderDTO
		{
			Id = o.Id,
			OrderDetails = o.OrderDetails.ConvertAll(od => new OrderDetailDTO
			{
				Id = od.Id,
				Count = od.Count,
				UnitPrice = od.UnitPrice
			}),
			OrderNo = o.OrderNo,
			Price = o.Price
		}),
		Phone = c.Phone
	}).ToList();
}
```
BTW, I think other mappers support collection mapping, so it's possible to map without `ToList`

For instance,  there's no `Select`

```
        public void BatMap() {
            var customerDTOs = _customers.Map<Customer, CustomerDTO>().ToList();
        }
```

but here's `Select` and `ToList`

```
        [Benchmark]
        public void TinyMapper() {
            var customerDTOs = _customers.Select(c => Nelibur.ObjectMapper.TinyMapper.Map<Customer, CustomerDTO>(c)).ToList();
        }

        [Benchmark]
        public void ExpressMapper() {
            var customerDTOs = _customers.Select(c => global::ExpressMapper.Mapper.Map<Customer, CustomerDTO>(c)).ToList();
        }
```
for any performance comparisonce, it's really impotant compare the same things in an equeal environment.

**Comment by umutozel** [comment]
Thanks for the feedback.
I will change the code at first chance and update the results.

**Comment by umutozel** [comment]
Sorry for the late reply, I was on a really long holiday :)

I wrote the handwritten test this way because I wanted the expression to be usable with projection and be available in .net core.

But you're right, this results might be misleading (especially for we are not doing benchmark for IQueryable projection).
