### ISSUE TITLE
Mapper.Map<TSource, TDestination>() not work when TDestination not have parameterless public ctor

### ISSUE THREAD

**Issue by swtanggara** [DogusTeknoloji/BatMap#5]
## BatMap version
1.1.3 (from NuGet)

## Steps to reproduce
```c#
Mapper.RegisterMap(typeof(MyEntity), typeof(MyDto)); // MyDto doesn't have parameterless public ctor
var dto = Mapper.Map<MyEntity, MyDto>(new MyEntity(1, "Bla"));
```

## Expected  behavior
```c#
dto.Id.Equals(1);
dto.Name.Equals("Bla");
```

## Actual behavior
```c#
dto.Id.Equals(0);
dto.Name.Equals(string.Empty);
```

@umutozel @onselakin @unalkarakus ?

**Comment by umutozel** [comment]
Thank you for the feedback, I will check it as soon as possible.

**Comment by aozmez** [comment]
Indigo içindeki versiyon için Unit test yazdım, benim makinamda çalışıyor.
:):):)

**Comment by umutozel** [comment]
@swtanggara can you share your MyEntity and MyDto code?

**Comment by swtanggara** [comment]
hi @umutozel here is the code:

```c#
public class MyDto
{
   public MyDto(int id, string name)
   {
      Id = id;
      Name = name;
   }
   
   public int Id { get; }
   public string Name { get; }
}

public class MyEntity
{
   public MyEntity(int id, string name)
   {
      Id = id;
      Name = name;
   }
   
   public int Id { get; }
   public string Name { get; }
}
```

**Comment by umutozel** [comment]
I thought about a solution for finding a way to support constructors with parameters but guessing which member maps to which parameter is not healthy. I can suggest two solutions;

- You can add setters for your properties on your Dto, but I'm guessing this is not a thing you want
- You can create the mapping using full expression. Beware, if you use constructors on your mapping expression IQueryable projections won't work correctly, so you cannot convert a Entity query to Dto query. But you can use it for object mappings. Here is an example:

`
Mapper.RegisterMap< MyEntity, MyDto >((e, mc) => new MyDto(e.Id, e.Name));
`

This way you tell BatMap to use given expression, not to create one.

I've added a test named Map_For_Constructor_With_Parameter to ConfigurationTests.
